Update ods-control to work the same on Enforcer as Signer now that they are almost the same

diff --git a/tools/ods-control.in b/tools/ods-control.in
--- a/tools/ods-control.in
+++ b/tools/ods-control.in
@@ -31,6 +31,7 @@ progname="ods-control"
 bindir="@OPENDNSSEC_BIN_DIR@"
 sbindir="@OPENDNSSEC_SBIN_DIR@"
 enforcer_pid_file="@OPENDNSSEC_ENFORCER_PIDFILE@"
+enforcer_socket_file="@OPENDNSSEC_ENFORCER_SOCKET@"
 signer_pid_file="@OPENDNSSEC_SIGNER_PIDFILE@"
 signer_socket_file="@OPENDNSSEC_SIGNER_SOCKET@"
 
@@ -93,25 +94,40 @@ case "$1" in
 	'start')
 		echo "Starting enforcer..."
 		"$sbindir/ods-enforcer" start
-		i=0
-		while [ ! -r "$enforcer_pid_file" ]; do
-			sleep 1
-			i=`expr $i + 1`
-			if [ $i -ge 5 ]; then
-				RETVAL=1
-				echo "Could not start enforcer"
-				exit $RETVAL
-			fi
-		done
-
-		"$sbindir/ods-enforcer" running
+		
 		RETVAL=$?
+		if [ $RETVAL = 0 ]; then
+			i=0
+			while [ ! -r "$enforcer_pid_file" ]; do
+				sleep 1
+				i=`expr $i + 1`
+				if [ $i -ge 5 ]; then
+					RETVAL=1
+					echo "Could not start enforcer"
+					exit $RETVAL
+				fi
+			done
+			i=0
+			while [ ! -r "$enforcer_socket_file" ]; do
+				sleep 1
+				i=`expr $i + 1`
+				if [ $i -ge 5 ]; then
+					RETVAL=1
+					echo "Could not start enforcer"
+					exit $RETVAL
+				fi
+			done
+			sleep 1
 
+			"$sbindir/ods-enforcer" running
+			RETVAL=$?
+		fi
+		
 		exit $RETVAL
 		;;
-
 	*)
-		"$sbindir/ods-enforcer" $2
+		shift
+		"$sbindir/ods-enforcer" "$@"
 		;;
 
 	esac
