and in trunk...

diff --git a/tools/ods-control.in b/tools/ods-control.in
--- a/tools/ods-control.in
+++ b/tools/ods-control.in
@@ -80,25 +80,20 @@ case "$1" in
 	case "$2" in
 
 	'start')
-		if [ -r "$enforcer_pid_file" ]; then
-			echo "Enforcer is already running"
-			RETVAL=1
-		else
-			echo "Starting enforcer..."
-			"$sbindir/ods-enforcerd"
-			RETVAL=$?
-			if [ $RETVAL = 0 ]; then
-				i=0
-				while [ ! -r "$enforcer_pid_file" ]; do
-					sleep 1
-					i=`expr $i + 1`
-					if [ $i -ge 5 ]; then
-						RETVAL=1
-						echo "Could not start enforcer"
-						break
-					fi
-				done
-			fi
+		echo "Starting enforcer..."
+		"$sbindir/ods-enforcerd"
+		RETVAL=$?
+		if [ $RETVAL = 0 ]; then
+			i=0
+			while [ ! -r "$enforcer_pid_file" ]; do
+				sleep 1
+				i=`expr $i + 1`
+				if [ $i -ge 5 ]; then
+					RETVAL=1
+					echo "Could not start enforcer"
+					break
+				fi
+			done
 		fi
 		exit $RETVAL
 		;;
